In [ ]:
import numpy as np
import pandas as pd
import re
import seaborn as sns
import sklearn as sk
import sklearn.model_selection

The notebook relies on `dir` to locate the directory storing our data, in the form of csv files

In [ ]:
dir = '../data'

# load data

In [ ]:
df = pd.read_csv( f'{dir}/nlpdata-8606.csv', encoding='utf8' )
### remove "special" characters
for c in df.columns:
  df[ c ] = df[ c ].apply( lambda x: re.sub( r' *[^\x00-\x7F]+', '', x ) if pd.notnull( x ) else x ).astype( 'string' )
print( df.shape )
df.head()

(8583, 7)

,kewords,Label,Question,Answer,topic,sub-topic,source
0,<NA>,<NA>,What were the sources of atmospheric nutrients...,The primary sources of atmospheric nutrients t...,<NA>,<NA>,<NA>
1,<NA>,<NA>,How was the fertilization effect on phytoplank...,The fertilization effect on phytoplankton was ...,<NA>,<NA>,<NA>
2,<NA>,<NA>,How do rising temperatures affect Alpine lakes?,Rising temperatures increase mineral weatherin...,<NA>,<NA>,<NA>
3,<NA>,<NA>,How has an increase in phytoplankton biomass b...,Significant increase in phytoplankton biomass ...,<NA>,<NA>,<NA>
4,<NA>,<NA>,How do higher metabolic rates of organisms and...,Higher metabolic rates of organisms and longer...,<NA>,<NA>,<NA>

In [ ]:
df.describe( include='all' )

,kewords,Label,Question,Answer,topic,sub-topic,source
count,0,0,8582,8577,0,0,0
unique,0,0,8505,8553,0,0,0
top,NaN,NaN,What is the purpose of this study?,The authors declare that they have no known co...,NaN,NaN,NaN
freq,NaN,NaN,12,6,NaN,NaN,NaN

In [ ]:
df.Question.isna().sum()

1

In [ ]:
df.Answer.isna().sum()

6

In [ ]:
df[ df.Question.duplicated() ]

,kewords,Label,Question,Answer,topic,sub-topic,source
211,<NA>,<NA>,What is the purpose of this study?,The purpose of this study is to compare the co...,<NA>,<NA>,<NA>
700,<NA>,<NA>,What is the source of funding for this study?,Funding for this study was provided by the Nat...,<NA>,<NA>,<NA>
748,<NA>,<NA>,What is the priming effect?,The priming effect is the process by which lab...,<NA>,<NA>,<NA>
863,<NA>,<NA>,What is the purpose of this study?,The purpose of this study is to explore the pe...,<NA>,<NA>,<NA>
1039,<NA>,<NA>,What was the title of the article?,The title of the article is Improving Estimate...,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...
7980,<NA>,<NA>,What does Table 3 show?,Table 3 shows the mass and energy balances per...,<NA>,<NA>,<NA>
8136,<NA>,<NA>,How can data be made available?,Data will be made available on request.,<NA>,<NA>,<NA>
8187,<NA>,<NA>,What is the main focus of the paper?,The main focus of the paper is to develop a co...,<NA>,<NA>,<NA>
8464,<NA>,<NA>,What is the goal of the energy transition?,The goal of the energy transition is to reduce...,<NA>,<NA>,<NA>
8564,<NA>,<NA>,What is the Declaration of Competing Interest?,The Declaration of Competing Interest is a sta...,<NA>,<NA>,<NA>

# drop items with empty question or answer

In [ ]:
df[ df.Question.isna() | df.Answer.isna() ]

,kewords,Label,Question,Answer,topic,sub-topic,source
82,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
87,<NA>,<NA>,What is the primary topic of the paper by Lu,<NA>,<NA>,<NA>,<NA>
166,<NA>,<NA>,What is the main factor of multi-dimensional w...,<NA>,<NA>,<NA>,<NA>
167,<NA>,<NA>,How can freshwater fisheries meet the demands ...,<NA>,<NA>,<NA>,<NA>
2476,<NA>,<NA>,What is the objective of this paper?,<NA>,<NA>,<NA>,<NA>
2498,<NA>,<NA>,What kind of context did the research by Chen ...,<NA>,<NA>,<NA>,<NA>

In [ ]:
df.dropna( subset=[ 'Question', 'Answer' ], inplace=True )
print( df.shape )
df.head()

(8577, 7)

,kewords,Label,Question,Answer,topic,sub-topic,source
0,<NA>,<NA>,What were the sources of atmospheric nutrients...,The primary sources of atmospheric nutrients t...,<NA>,<NA>,<NA>
1,<NA>,<NA>,How was the fertilization effect on phytoplank...,The fertilization effect on phytoplankton was ...,<NA>,<NA>,<NA>
2,<NA>,<NA>,How do rising temperatures affect Alpine lakes?,Rising temperatures increase mineral weatherin...,<NA>,<NA>,<NA>
3,<NA>,<NA>,How has an increase in phytoplankton biomass b...,Significant increase in phytoplankton biomass ...,<NA>,<NA>,<NA>
4,<NA>,<NA>,How do higher metabolic rates of organisms and...,Higher metabolic rates of organisms and longer...,<NA>,<NA>,<NA>

In [ ]:
df[ df.Question.isna() | df.Answer.isna() ]

Empty DataFrame
Columns: [kewords, Label, Question, Answer, topic, sub-topic, source ]
Index: []

In [ ]:
df.to_csv( f'{dir}/nlpdata-8606-cleansed.csv', index=False, encoding='utf8' )